import { Inter } from 'next/font/google';
import './ui/globals.css';
import AuthGuard from './lib/authGuard';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthGuard children={children}/>
        
        </body>
    </html>
  )
}
